name: Deploy to VM

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy and restart with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.SSH_USER }}/app/vercel-clone"
            APP_NAME="vercel-be"
            
            cd $DEPLOY_PATH || ( mkdir -p "$DEPLOY_PATH" && git clone "https://github.com/GeneCodeSavvy/vercel-clone.git" "$DEPLOY_PATH" && cd "$DEPLOY_PATH" )

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm use || nvm install node --default || { echo "Error: Failed to use or install Node.js"; exit 1; }

            git switch deployment || { echo "Error: Failed to switch to branch 'deployment'"; exit 1; }
            
            git fetch origin || { echo "Error: Failed to fetch from origin"; exit 1; }
            
            git reset --hard origin/deployment || { echo "Error: Failed to perform hard reset"; exit 1; }
            
            git clean -df || { echo "Error: Failed to clean untracked files"; exit 1; }

            npm run install:all || { echo "Error: Failed to run npm install"; exit 1; }

            if ! which pm2 > /dev/null; then
              echo "PM2 not found. Installing PM2 globally."
              npm install -g pm2
            fi

            if pm2 describe $APP_NAME > /dev/null; then
              echo "PM2 app $APP_NAME found. Reloading..."
              pm2 reload $APP_NAME || { echo "Error: Failed to reload PM2 app $APP_NAME"; exit 1; }
            else
              echo "PM2 app $APP_NAME not found. Starting pm2."
              pm2 start npm --name vercel-be --run start:all || { echo "Error: Failed to start PM2 app $APP_NAME"; exit 1; }
            fi
